
### criar lailão
POST http://localhost:8080/auction
Content-Type: application/json

{
    "product_name": "ferrari32",
    "category": "automovel1",
    "description": "testes de automovel",
    "condition": 0
}


### aguarda o tempo definido na variável de ambiente e realizar a consulta abaixo
GET http://localhost:8080/auction?status=1